### ISSUE TITLE
Consider enabling delete_branch_on_merge

### ISSUE THREAD

**Issue by merks** [eclipse-simrel/simrel.build#184]
Now that we have support for auto-merge via https://github.com/eclipse-simrel/simrel.build/issues/103 should we also enable delete_branch_on_merge so that one really has to do nothing else manually if the verification build succeeds?

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4156#note_1612521

@jonahgraham @ruspl-afed @akurtakov

**Comment by jonahgraham** [comment]
Yes we should.

**Comment by merks** [comment]
The change is pending.
