### ISSUE TITLE
SimRel Oomph setup is broken

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-simrel/simrel.build#206]
Using latest Oomph (1.32.0 Build 418) the SimRel setup doesn't work. After the IDE installs and starts I can see the setup check run briefly, but then nothing further happens.

There is an error log entry that says: `The location '/scratch/eclipse/oomph/simrel-main3/git/simrel.github' is not empty but is not a Git repository.` and the contents of the mentioned directory are:

```
$ tree -a $PWD
/scratch/eclipse/oomph/simrel-main3/git/simrel.github
├── .gitignore
├── .project
└── .settings
    └── org.eclipse.core.resources.prefs

1 directory, 3 files
```

I tried this on a Linux and Windows machine and got the same results.

**Comment by jonahgraham** [comment]
I have a SimRel Oomph that I created on Jan 10 and that still works. On that one if I run Help -> Perform Setup Tasks it updates to latest version, restarts and continues to work.

**Comment by nitind** [comment]
Going by that directory listing, the message is correct--there is no .git directory.

**Comment by jonahgraham** [comment]
> Going by that directory listing, the message is correct--there is no .git directory.

Yes that is correct. Unfortunately it seems to be the Oomph setup that created that directory as `/scratch/eclipse/oomph/simrel-main3` was created by the process.

**Comment by merks** [comment]
Sorry I probably messed that file creation task up. It should only trigger in the ide not bootstrap (advanced properties) and be after the git clone task. Unfortunately I can’t fix this until Friday.  Hopefully if you manually remove the clone folder and restart it will work. Sorry.

**Comment by jonahgraham** [comment]
Your workaround worked. I did `rm -r git/simrel.github/` with Eclipse closed\* and started the Eclipse again. The setup tasks ran to completion and a new clone was made.

\* I don't know if I had to close Eclipse, but it seemed prudent.
