### ISSUE TITLE
"Mirror tool: Problems resolving provisioning plan" error with latest 2024-06 repo

### ISSUE THREAD

**Issue by Phillipus** [eclipse-simrel/simrel.build#399]
Apologies if I'm jumping the gun here by targetting the repo at `https://download.eclipse.org/staging/2024-06` but I like to test our product against the latest builds so I thought I better report this in case there's a problem.

Our `.product` file includes the following feature:

```
<feature id="org.eclipse.ecf.filetransfer.httpclient5.feature"/>
```

Now when we try to build our product using Tycho (4.0.8) and our `pom.xml` targetting the staging repo the build is unsuccessful:

[WARNING] Mirror tool: Problems resolving provisioning plan.:
   Unable to satisfy dependency from org.eclipse.ecf.filetransfer.httpclient5.feature.feature.group 1.1.702.v20231114-1017 to org.eclipse.equinox.p2.iu; org.eclipse.ecf.provider.filetransfer.httpclient5.win32 [1.1.0.v20230423-0417,1.1.0.v20230423-0417], filter=(osgi.os=win32).
   Unable to satisfy dependency from org.eclipse.ecf.filetransfer.httpclient5.feature.feature.group 1.1.702.v20231114-1017 to org.eclipse.equinox.p2.iu; org.apache.httpcomponents.client5.httpclient5-win [5.2.1.v20230802-0847,5.2.1.v20230802-0847], filter=(osgi.os=win32).

and:

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-director-plugin:4.0.7:materialize-products (create-distributions) on project com.archimatetool.editor.product: Installation of product com.archimatetool.editor.product for environment win32/win32/x86_64 failed: Call to p2 director application failed:Cannot complete the install because one or more required items could not be found.: [Software being installed: Archi 5.4.0.202405311403 (com.archimatetool.editor.product 5.4.0.202405311403); Missing requirement for filter properties ~= $0: ECF Apache Httpclient 5 FileTransfer Provider 1.1.702.v20231114-1017 (org.eclipse.ecf.filetransfer.httpclient5.feature.feature.group 1.1.702.v20231114-1017) requires 'org.eclipse.equinox.p2.iu; org.eclipse.ecf.provider.filetransfer.httpclient5.win32 [1.1.0.v20230423-0417,1.1.0.v20230423-0417], filter=(osgi.os=win32)' but it could not be found; Cannot satisfy dependency:: [From: Archi 5.4.0.202405311403 (com.archimatetool.editor.product 5.4.0.202405311403); To: org.eclipse.equinox.p2.iu; org.eclipse.ecf.filetransfer.httpclient5.feature.feature.group [1.1.702.v20231114-1017,1.1.702.v20231114-1017]]].

**Comment by Phillipus** [comment]
Actually, the error is occurring not just with the staging repo, but also with the `releases` repo at `https://download.eclipse.org/releases/2024-06`

**Comment by merks** [comment]
The bundle from the warning is present:

![image](https://github.com/eclipse-simrel/simrel.build/assets/208716/7b17b830-b460-49c6-ac47-54c0e0b8a731)

From the qualifier versions, all this content is the same as in the previous release, i.e., ECF has not updated its contribution for this release cycle.

The warning is the same one we noticed in the EPP build:

https://github.com/eclipse-packaging/packages/issues/171

Is the feature requirement specified directly in the produce as a non-root feature?

**Comment by Phillipus** [comment]
> Is the feature requirement specified directly in the produce as a non-root feature?

non-root, but I also tried it as a root feature and still the same error.

**Comment by merks** [comment]
I'm trying to see if I can reproduce this with an EPP build locally....

**Comment by Phillipus** [comment]
Attached is a simple reproducer. Unzip and `mvn clean verify`

[test.zip](https://github.com/user-attachments/files/15515681/test.zip)

**Comment by merks** [comment]
Yes, the EPP build fails too when I add it as a root feature in the product.  Also with older versions of Tycho. So perhaps a workaround is to import it into a feature.  I will continue to investigate.  A smaller/simpler example should be very helpful.

**Comment by Phillipus** [comment]
>  A smaller/simpler example should be very helpful.

Is the example in the comment above not simple/small enough?

**Comment by merks** [comment]
The parent pom is missing.

**Comment by Phillipus** [comment]
> The parent pom is missing.

It's there in the `test` folder as well as the pom in the `product` folder. Try unzipping again?

**Comment by merks** [comment]
Ah I did import existing projects and that only found the nested content...

**Comment by Phillipus** [comment]
> Ah I did import existing projects and that only found the nested content...

Yeah, the `.project` file shouldn't be there. I tried to make it standalone so you can just run `mvn clean verify` from the command line.

**Comment by merks** [comment]
The same is very helpful now.  There is some difference between M2 and RC1 that makes things fails.

But it's late in the day for me, so I will continue to investigate first thing.

None thing that's already disconcerting is that while M2 has one such feature:

![image](https://github.com/eclipse-simrel/simrel.build/assets/208716/1968e31e-821c-4c57-8255-c660d4ed8db2)

RC1 has two of them:

![image](https://github.com/eclipse-simrel/simrel.build/assets/208716/2dfb0e1e-ec08-4e39-87b7-573f1aa85d8a)

**Comment by Phillipus** [comment]
> One thing that's already disconcerting is that while M2 has one such feature
> RC1 has two of them

And the Platform I-builds have just the one:

https://download.eclipse.org/eclipse/updates/4.32-I-builds/I20240529-1800/features/

<img width="869" alt="Screenshot 2024-05-31 at 17 10 54" src="https://github.com/eclipse-simrel/simrel.build/assets/600504/932f0732-3b53-41e5-876f-12735a850acb">

**Comment by merks** [comment]
Of course.  The old one is coming from here:

![image](https://github.com/eclipse-simrel/simrel.build/assets/208716/207d0ff0-a36d-43bd-a4b3-af5a06051229)

It's just not clear why it's being pulled in now and not before.

When I get rid of the GEF FX related stuff then Papyrus is missing javax.annotation which also comes from the old fx thing.  What a nightmare mess.  😱

**Comment by Phillipus** [comment]
And differences in `org.apache.httpcomponents.client5.httpclient5`.

M2:

<img width="964" alt="Screenshot 2024-05-31 at 17 31 21" src="https://github.com/eclipse-simrel/simrel.build/assets/600504/0a972ce6-3458-4b51-b7da-bff61fdc7041">

RC1:

<img width="983" alt="Screenshot 2024-05-31 at 17 32 17" src="https://github.com/eclipse-simrel/simrel.build/assets/600504/a923e111-c06f-48da-9c08-4fc6a3689815">

**Comment by merks** [comment]
FYI, I tried adding an exclusion rule:

![image](https://github.com/eclipse-simrel/simrel.build/assets/208716/d8c08f6b-3442-40a8-a96e-1081712ea856)

That did eliminate the duplicates:

![image](https://github.com/eclipse-simrel/simrel.build/assets/208716/4fdc8b89-2353-4f78-8bbc-e5901e729a6b)

So I'm building the aggregation locally so I can test that it fixed the problem locally...

But that takes pretty long...

**Comment by merks** [comment]
Thank you for:

- Testing early.
- Reporting promptly.
- Providing a super simple test case.

The build now succeeds for the just-built staging repository:

![image](https://github.com/eclipse-simrel/simrel.build/assets/208716/699ea583-df94-40a4-8e5e-113c6d32bb37)

Note I had to specify -U so it would load it freshly...

**Comment by Phillipus** [comment]
I've tested the latest staging repo with our product and all seems to be well. Thanks @merks for your heroic efforts here (and everywhere)!
