### ISSUE TITLE
Update or remove .mailmap?

### ISSUE THREAD

**Issue by merks** [eclipse-simrel/simrel.build#403]
I'm not sure the purpose of this file:

https://github.com/eclipse-simrel/simrel.build/blob/main/.mailmap

With the changes for https://github.com/eclipse-simrel/simrel.build/pull/402 the list of contracts has been cleaned up and updated.

But given I don't know the purpose of .mailmap, there is little point in updating it, especially manually, if it's not actually used for anything.

@jonahgraham 

Do you know the purpose of this file?

**Comment by Phillipus** [comment]
https://www.git-scm.com/docs/gitmailmap

https://ntietz.com/blog/git-mailmap-for-name-changes/

**Comment by merks** [comment]
I see. I think I will just leave it as is and effectively ignore it.  Anyone who wants to maintain it could do so.
