### ISSUE TITLE
SimRel Project Logo

### ISSUE THREAD

**Issue by merks** [eclipse-simrel/simrel.build#47]
Our creative graphic designers have created the following artwork for the SimRel project's logo:

[SimRel_Logo.pdf](https://github.com/eclipse-simrel/simrel.build/files/13317389/SimRel_Logo.pdf)

Please vote below with a 👍 on your favorites.  Note that you can remove a "reaction" by clicking on the "icon".

**Comment by merks** [comment]
A)

![image](https://github.com/eclipse-simrel/simrel.build/assets/208716/94e64187-554a-4b66-9393-54e3ba0209d0)

**Comment by merks** [comment]
B)

![image](https://github.com/eclipse-simrel/simrel.build/assets/208716/f3f66854-fded-46df-a98c-0334e9a4b847)

**Comment by merks** [comment]
C)

![image](https://github.com/eclipse-simrel/simrel.build/assets/208716/256db220-97ad-4fef-abba-b161faf795fe)

**Comment by laeubi** [comment]
@merks you probably want to make a "poll discussion" instead...

**Comment by merks** [comment]
If I knew how...  In any case, it's not like we're voting for President.  Not only that, as team lead I have dictatorial powers so I will take the votes as advice.  😱

**Comment by laeubi** [comment]
Go to https://github.com/orgs/eclipse-simrel/discussions then
![grafik](https://github.com/eclipse-simrel/simrel.build/assets/1331477/bb67419e-3ad4-4dcf-9c34-e3b24dffbfdb)

**Comment by estepper** [comment]
I like B most, then C, and A not at all ;-)

**Comment by lfasani** [comment]
Hello
I prefer C) because of the connected circle that give the idea of an assembly of linked features (that simrel is)
B) is ok
I dislike A)

**Comment by merks** [comment]
It's fine to comment here, but please also ensure that the reactions are on the A, B, or C so I can review the numbers easily.

**Comment by jonahgraham** [comment]
I added reactions.. For my favs. While I prefer B, I have to call out for a job well done to graphics on this. I really like how option C has S and R in the logo.

**Comment by HeikoKlare** [comment]
I also really like the designs and voted for option B. But I have to admit that I would actually prefer a non-orange font for the "SimRel" text, like the ones in option A or C.

**Comment by merks** [comment]
> I also really like the designs and voted for option B. But I have to admit that I would actually prefer a non-orange font for the "SimRel" text, like the ones in option A or C.

Yes, I personally like the two-tone label on option A the best.  I personally really like B and C and I thought that B would also make a really good Orbit logo, which is also in need of a logo...

**Comment by laeubi** [comment]
You coukd ask for a vriant with a different font color I think...

**Comment by merks** [comment]
Yes, this is not the final artwork which will include various versions, sizes, and formats and I will ask for that.
