### ISSUE TITLE
Stale simrel.aggran

### ISSUE THREAD

**Issue by ewillink** [eclipse-simrel/simrel.build#659]
I was endeavouring to check an upgrade of qvto.setup to the new github repo spelling, but was unable to use the new repo spelling. The Oomph installer offers the old spelling.

Searching my workspace for a rogue residual git.eclipse.org/r/mmt/org.eclipse.qvto, I found one in simrel.aggran; presumably this is what the Oomph installer uses regardless of the GitCloneTask.

Checking to see whether it was 'my fault', I found five stale references for MoDisco, OCL, QVTd, QVTo, TM (4/5 'my fault'). But it appears that simrel.aggran is maintained by Ed Merks rather than individual relengs, so not 'my fault'.  But why Ed Merks? Surely a specific/generic EF team member should update when the PMI is updated? Or some genie should synchronize simrel.aggran with the PMI.

Anyway, please ensure that simrel.aggran is regularly refreshed.

**Comment by merks** [comment]
Please don’t bother. This file is updated by a generator. I’ll run it when I have some time soon.

**Comment by merks** [comment]
It's updated by Reconcile Projects on the context, but I prefer to hand hold that process because there are often glitches in the project metadata that's being analyzed, or repositories are added to are not contributing content to simrel.

**Comment by ewillink** [comment]
I refer to the migration guide that the EF should have produced to reduce the pain inflicted on them by the GIT change.

Of course it's a bit late now. But not too late for some centralised OOMPH script to detect the many *.setup that were as defective  as mine. Else many OOMPH setups will appear to work but will actually be using the stale e.g. emf/org.eclipse.emf that is not redirected to GitHub.
